version: "3.8"

services:
  app:
    container_name: graph_generator
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8088 --reload"
    volumes:
      - .:/app
    ports:
      - 8088:8088
    restart: always

